# Numpy part 1

Numpy:

        Numpy is a general purpose array processing package which provides a high performance multidimensional array object and tools for working with these arrays.        source: GeekforGeeks

In [1]:
# creating numpy arrays

Arrays in numpy can be created by multiple ways, with various number of ranks, defining the size of the array. Array can also be created with the use of various data types such as lists, tuple, etc.

In [2]:
# creating rank1 array
import numpy as np

In [3]:
arr1 = np.array([1,2,3])

arr1

array([1, 2, 3])

In [4]:
# creating rank2 array

In [6]:
arr2 = np.array([[1,2,3]
                 ,[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# creating array from tuple

arr3 = np.array((1,4,5))

In [8]:
print("array using tuple is : ",arr3)

array using tuple is :  [1 4 5]


In [9]:
# accessing the array index

"""
in numpy, indexing or accessing the array index can be done in multiple ways. to print a range of array, slicing is done.

slicing is the array which is defined with a range in a new array which is used to print a range of elements from the original array.
"""

'\nin numpy, indexing or accessing the array index can be done in multiple ways. to print a range of array, slicing is done.\n\nslicing is the array which is defined with a range in a new array which is used to print a range of elements from the original array.\n'

In [11]:
# initial array
arr_in = np.array([[2,4,5,0],
                   [3,6,-1,4],
                   [2,4,7,5],
                   [1,3,8,9]])

In [13]:
print("Initial array : ")
arr_in

Initial array : 


array([[ 2,  4,  5,  0],
       [ 3,  6, -1,  4],
       [ 2,  4,  7,  5],
       [ 1,  3,  8,  9]])

In [14]:
# new array using slicing to return a range of arrays

In [17]:
slice_arr = arr_in[:1,::3]
print("Arrays with first one rows and alternate columns are")
slice_arr

Arrays with first one rows and alternate columns are


array([[2, 0]])

In [18]:
# elements at specific index
index_arr = slice_arr